apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replica-config
data:
  postgresql.conf: |
    wal_level = replica
    hot_standby = on
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby_feedback = on
  pg_hba.conf: |
    host    replication     reptest       0.0.0.0/0       md5
    host    all             all           0.0.0.0/0       md5
