apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
  labels:
    app: postgres
    role: replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
