apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
  labels:
    app: postgres
    role: master
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30002
  selector:
    app: postgres
    role: master
  

  
