apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
  labels:
    app: postgres
    role: master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
