apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  labels:
    app: postgres
    role: replica
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
    role: replica
  clusterIP: None
