apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replica-config
data:
  replica.sh: |
    #!/bin/bash
    set -e
    if [ ! -s "$PGDATA/PG_VERSION" ]; then
      pg_basebackup -h $POSTGRES_MASTER_SERVICE_HOST -D $PGDATA -U $POSTGRES_REPLICATION_USER -vP -W
    fi
    exec postgres
