apiVersion: v1
kind: Secret
metadata:
  name: postgres-master-secret
type: Opaque
data:
  POSTGRES_USER: dGVzdA==  # Base64 de 'test'
  POSTGRES_PASSWORD: dGVzdA==   # Base64 de 'test'
  
# comand to encond    echo -n 'admin' | base64