apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
  pg_hba.conf: |
    host replication replicator 0.0.0.0/0 md5
