apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: PiCloud
    tier: api-app
    environment: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: PiCloud
      tier: api-app
      environment: dev
  template:
    metadata:
      labels:
        app: PiCloud
        tier: api-app
        environment: dev
    spec:
      containers:
      - name: api-app
        image: filipe3paisana/backend-image:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
          - containerPort: 8080