apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  selector:
    app: PiCloud
    tier: api-app
    environment: dev
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001  # Especifica a porta NodePort (escolha uma entre 30000 e 32767)
  type: NodePort
