apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: PiCloud
    tier: web-app
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Especifica a porta NodePort
  type: NodePort
